GET http://localhost:3000/projects
token: eyJhbGciOJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZjljY2RhMi1iNjdhLTQzNmMtODc2NC1jNzA3ZWI4YmQxNzMiLCJuYW1lIjoiYW1vcyIsImVtYWlsIjoiYW1vc0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY4Njg1MzkzMSwiZXhwIjoxNjg2ODU3NTMxfQ.yWZVju7h0qjzZGHGPhDaq3-2agTZiwlLjOfb2XOtOCk