GET http://localhost:3000/projects
token: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZjljY2RhMi1iNjdhLTQzNmMtODc2NC1jNzA3ZWI4YmQxNzMiLCJuYW1lIjoiYW1vcyIsImVtYWlsIjoiYW1vc0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY4Njg1NDc2NywiZXhwIjoxNjg2ODU4MzY3fQ.BWPLt46T8g4UmG-UIVEH7HTDAKynJ7RbDkExkxxZLcg