CREATE TABLE users (userId VARCHAR(200) UNIQUE PRIMARY KEY, email VARCHAR(200) UNIQUE, password VARCHAR(200), confirmPassword VARCHAR(200), role VARCHAR(50) DEFAULT 'user');

CREATE TABLE projects (projectId VARCHAR(200) UNIQUE PRIMARY KEY, title VARCHAR(50), description VARCHAR(200), scope VARCHAR(200),userId VARCHAR, FOREIGN KEY (userId) REFERENCES users (userId));